name: enroll_me
description: A Cross Platform Event Management Application for Organisations.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For network interactions
  http: ^0.13.5

  # Beautiful bottom navigation bar
  bottom_navy_bar: ^6.0.0

  # Includes iOS icons
  cupertino_icons: ^1.0.5

  #For making chat bubbles like in whatsapp (https://pub.dev/packages/bubble)
  bubble: ^1.2.1

  # ui elements and layouts
  groovin_widgets: ^3.1.0

  # custom animated pull to refresh indicator
  liquid_pull_to_refresh: ^3.0.1

  # ui elements to display profile tags
  flutter_tags: ^0.4.9+1

  # to use svg inside flutte project
  flutter_svg: ^1.1.6

  # extended icon library for flutter
  font_awesome_flutter: ^10.2.1

  # to get different custom shapes and borders
  flutter_custom_clippers: ^2.0.0

  # To authenticate users
  firebase_auth: ^4.1.3

  # database for app
  cloud_firestore: ^4.1.0

  #for google-sign in OAuth
  google_sign_in: ^5.4.2

  #for state management of app
  provider: ^6.0.4

  # for reactive programming
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/welcome.svg
   - assets/images/homepage.svg
   - assets/images/card.svg
   - assets/images/teamwork.svg
   - assets/images/create-meetup.svg
   - assets/images/emailLogin.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Product-Sans
      fonts:
        - asset: assets/fonts/product-sans/ProductSansRegular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
